"""
Hilo People — SQLAlchemy 2.x ORM models: chat conversations.

Slice:  P02-S01-T001 — 0002_ai_chat_rag_mcp_agents migration
Phase:  P02 Core Features (the motor)
Purpose: Defines ORM models for the chat conversation bounded context:
         Conversation, Message, MessageCitation.

Bounded context: chat — conversation threads, messages from users/assistants,
and RAG citation metadata attached to assistant messages. The LlmUsageLog
model lives in admin_ai.py because it is shared by the Admin AI dashboard.

Mapped tables (all created by migration 0002_ai_chat_rag_mcp_agents.py):
  - conversations    (FK -> users ON DELETE CASCADE)
  - messages         (FK -> conversations ON DELETE CASCADE)
  - message_citations (FK -> messages ON DELETE CASCADE; document_id/chunk_id
                       intentionally have NO FK — D-LATE; see below)

Key deps:
  - app.db.base              — Base (DeclarativeBase with naming_convention)
  - sqlalchemy==2.0.49       — Mapped, mapped_column, ForeignKey
  - sqlalchemy.dialects.postgresql — UUID

Decisions implemented:
  - D-LATE: message_citations.document_id and message_citations.chunk_id have
    NO FK constraints (source: §10.3 §I.1). Citations survive document
    deletion/versioning — breaking the FK would erase the trace of what
    the assistant cited. Consistency enforced at app layer (P02-S03+).
  - D-IDX (approved by user): conversations.language CHECK constraint
    conversations_language_chk ('es','en','fr') — coherence with users.preferred_language.
  - Timestamps: TIMESTAMPTZ (timezone=True) per §10.3 ADR-003 (UTC everywhere).

Source refs:
  - docs/source-of-truth/HILO_PEOPLE_TECHNICAL_GUIDE.md §10.3#chat
  - docs/source-of-truth/instrucciones.md §3.1#chat-rag
"""

from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


# ---------------------------------------------------------------------------
# Conversation — a chat thread owned by a user
# ---------------------------------------------------------------------------
class Conversation(Base):
    """ORM model for the `conversations` table.

    Represents a named chat thread initiated by an authenticated user.
    Each conversation has a language preference (same enum as users.preferred_language)
    and tracks created/updated timestamps for listing with pagination.

    Table: conversations
    PK: id UUID (gen_random_uuid())
    FK: user_id -> users.id ON DELETE CASCADE
    CHECK: conversations_language_chk (language IN ('es','en','fr')) — D-IDX
    Indexes: conversations_user_updated_idx (user_id, updated_at DESC) — §10.3

    Refs: §10.3#chat, instrucciones.md §3.1#chat-rag, D-IDX user-approved.
    """

    __tablename__ = "conversations"
    __table_args__ = (
        sa.CheckConstraint(
            "language IN ('es','en','fr')",
            name="conversations_language_chk",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        comment="PK UUID generated by pgcrypto gen_random_uuid()",
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey(
            "users.id",
            ondelete="CASCADE",
            name="conversations_user_id_fkey",
        ),
        nullable=True,
        comment="FK -> users.id ON DELETE CASCADE; NULL for anonymous/system conversations",
    )
    title: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        comment="Human-readable conversation title set by user or auto-generated",
    )
    language: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        server_default=sa.text("'es'"),
        comment="ISO 639-1 code; CHECK conversations_language_chk enforces es|en|fr (D-IDX)",
    )
    created_at: Mapped[sa.DateTime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )
    updated_at: Mapped[sa.DateTime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        comment="Updated by app layer when a new message is added",
    )


# ---------------------------------------------------------------------------
# Message — a single turn in a conversation (user or assistant)
# ---------------------------------------------------------------------------
class Message(Base):
    """ORM model for the `messages` table.

    Represents one message turn in a conversation. role can be 'user' or
    'assistant' (enforced at app layer, not at schema level — extensible for
    'system' or 'tool' roles in future MCP flows).

    token_count is populated by the LLM gateway after the response is received
    (nullable until the assistant message is complete).

    Table: messages
    PK: id UUID (gen_random_uuid())
    FK: conversation_id -> conversations.id ON DELETE CASCADE
    Indexes: messages_conversation_created_idx (conversation_id, created_at) — §10.3

    Refs: §10.3#chat, instrucciones.md §3.1#chat-rag.
    """

    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        comment="PK UUID generated by pgcrypto gen_random_uuid()",
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey(
            "conversations.id",
            ondelete="CASCADE",
            name="messages_conversation_id_fkey",
        ),
        nullable=False,
        comment="FK -> conversations.id ON DELETE CASCADE",
    )
    role: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        comment="Message role: 'user' or 'assistant'; enforced at app layer",
    )
    content: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        comment="Raw message content — NEVER log full content for PII reasons",
    )
    token_count: Mapped[int | None] = mapped_column(
        sa.Integer,
        nullable=True,
        comment="Total tokens consumed by this message (populated post-LLM response)",
    )
    created_at: Mapped[sa.DateTime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )


# ---------------------------------------------------------------------------
# MessageCitation — RAG source attribution for an assistant message
# ---------------------------------------------------------------------------
class MessageCitation(Base):
    """ORM model for the `message_citations` table.

    Represents a citation attached to an assistant message, linking back to
    a RAG document chunk and the retrieval score.

    IMPORTANT (D-LATE): document_id and chunk_id have NO FK constraints.
    Reason: citations must survive document deletion and versioning — a user
    reviewing old chat history should still see what source was cited, even
    if the original document was later deleted or updated. Referential
    integrity is maintained at the application layer (P02-S03 Chat service).

    Table: message_citations
    PK: id UUID (gen_random_uuid())
    FK: message_id -> messages.id ON DELETE CASCADE (citation is part of message)
    NO FK: document_id, chunk_id (D-LATE — see docstring above)

    Refs: §10.3#chat, instrucciones.md §3.1#chat-rag, §I.1 D-LATE decision.
    """

    __tablename__ = "message_citations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        comment="PK UUID generated by pgcrypto gen_random_uuid()",
    )
    message_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey(
            "messages.id",
            ondelete="CASCADE",
            name="message_citations_message_id_fkey",
        ),
        nullable=False,
        comment="FK -> messages.id ON DELETE CASCADE; citation belongs to the assistant message",
    )
    document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        comment=(
            "UUID of the cited document — intentionally NO FK (D-LATE). "
            "Citations survive document deletion for audit continuity."
        ),
    )
    chunk_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        comment=(
            "UUID of the specific document chunk — intentionally NO FK (D-LATE). "
            "Allows citation to persist after chunk re-vectorization."
        ),
    )
    label: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        comment="Human-readable citation label shown in UI (e.g. 'Doc title, p.3')",
    )
    score: Mapped[float] = mapped_column(
        sa.Float,
        nullable=False,
        comment="Cosine similarity retrieval score (0.0–1.0) from the vector search",
    )
