"""
SQLAlchemy ORM models: User, EmployeeProfile, and user_roles association table.

Slice: P01-S01-T001 — DB auth baseline
Phase: P01 — Auth + base capabilities

Tables declared here:
  - users             — core identity table (HILO_PEOPLE_TECHNICAL_GUIDE.md §10.3 lines 70-83)
  - employee_profiles — extended employee attributes (§10.3 lines 85-94)
  - user_roles        — M:N association between users and roles; lives here
                        because it owns the users.id FK side (SQLAlchemy
                        convention: association table follows the "owning" FK).

ON DELETE semantics (per §10.3 + task-pack P01-S01-T001 §12.2):
  - employee_profiles.user_id → ON DELETE CASCADE  (profile disappears with user)
  - user_roles.user_id         → ON DELETE CASCADE  (memberships disappear with user)

Check constraints:
  - users_language_chk: preferred_language IN ('es', 'en', 'fr')
    (01-non-negotiables.md §Production quality + instrucciones.md §3.1)

No logging here — pure SQLAlchemy declarative module.  See task-pack §8
for the explicit exemption (same pattern as presentational components).

Dependencies:
  - sqlalchemy 2.0.49
  - app.db.models.base.Base (naming convention + DeclarativeBase)
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.models.base import Base

if TYPE_CHECKING:
    from app.db.models.auth import AuditLog, MfaTotpSecret, PasswordResetToken, RefreshToken

# Association table for the M:N User ↔ Role relationship.
# Declared as a plain Table (not a mapped class) — no extra columns needed.
# Primary key covers both columns; GIN indexes added in migration.
# ON DELETE CASCADE on both FK sides (task-pack §7.2).
user_roles_table = sa.Table(
    "user_roles",
    Base.metadata,
    sa.Column(
        "user_id",
        sa.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.Column(
        "role_id",
        sa.UUID(as_uuid=True),
        sa.ForeignKey("roles.id", ondelete="CASCADE"),
        nullable=False,
    ),
    sa.PrimaryKeyConstraint("user_id", "role_id", name="pk_user_roles"),
)


class User(Base):
    """ORM model for the `users` table.

    Table: users (HILO_PEOPLE_TECHNICAL_GUIDE.md §10.3 lines 70-83)
    Slice: P01-S01-T001

    Columns declared exactly per §10.3.  No speculative columns added
    (R1 risk guard — task-pack §13).

    ON DELETE: this is the parent table — child tables reference users(id)
    with ON DELETE CASCADE or SET NULL (declared in their own models).

    password_hash is TEXT (not Binary) — Argon2 produces a string encoding;
    hashing/encryption services land in P01-S02-T001 and P02-S02-T001.

    preferred_language CHECK constraint enforces the 3 supported locales
    (instrucciones.md §3.1 "el idioma solo puede ser es, en o fr").
    """

    __tablename__ = "users"
    __table_args__ = (
        sa.CheckConstraint(
            "preferred_language IN ('es', 'en', 'fr')",
            name="users_language_chk",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        sa.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        doc="Primary key; generated by pgcrypto gen_random_uuid().",
    )
    email: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        doc="Corporate email — unique login identifier (§3.1 corporate-email rule).",
    )
    password_hash: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Argon2 password hash (§10.2). Hashing in P01-S02-T001.",
    )
    full_name: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Display name.",
    )
    status: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        server_default="active",
        doc="Account status: active | suspended | pending.",
    )
    preferred_language: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        server_default="es",
        doc="UI locale enforced by CHECK constraint (es|en|fr).",
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        doc="Row creation timestamp (UTC).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        onupdate=sa.func.now(),
        doc="Last-updated timestamp; managed by SQLAlchemy onupdate (no PG trigger).",
    )

    # Relationships (back-populated in auth models)
    employee_profile: Mapped[EmployeeProfile | None] = relationship(
        "EmployeeProfile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    refresh_tokens: Mapped[list[RefreshToken]] = relationship(  # type: ignore[name-defined]
        "RefreshToken",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    mfa_totp_secret: Mapped[MfaTotpSecret | None] = relationship(  # type: ignore[name-defined]
        "MfaTotpSecret",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    password_reset_tokens: Mapped[list[PasswordResetToken]] = relationship(  # type: ignore[name-defined]
        "PasswordResetToken",
        back_populates="user",
        cascade="all, delete-orphan",
    )
    audit_logs_acted: Mapped[list[AuditLog]] = relationship(  # type: ignore[name-defined]
        "AuditLog",
        back_populates="actor_user",
        foreign_keys="AuditLog.actor_user_id",
    )


class EmployeeProfile(Base):
    """ORM model for the `employee_profiles` table.

    Table: employee_profiles (HILO_PEOPLE_TECHNICAL_GUIDE.md §10.3 lines 85-94)
    Slice: P01-S01-T001

    1:1 extension of User — every employee has exactly one profile.
    user_id is both PK and FK to users(id) ON DELETE CASCADE (§10.3).

    metadata JSONB stores extra HR attributes that don't warrant dedicated
    columns (flexible for future org changes without migration).
    """

    __tablename__ = "employee_profiles"

    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
        doc="FK to users(id). ON DELETE CASCADE — profile disappears with the user.",
    )
    employee_id: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        doc="HR system employee identifier — unique across the company.",
    )
    brand: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Brand/division within the company.",
    )
    society: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Legal entity / society.",
    )
    center: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Work center identifier.",
    )
    country: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="ISO country code of employment.",
    )
    department: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        doc="Department name.",
    )
    metadata_col: Mapped[dict] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        server_default=sa.text("'{}'::jsonb"),
        doc="JSONB bag for future HR attributes without a schema migration.",
    )

    user: Mapped[User] = relationship(
        "User",
        back_populates="employee_profile",
    )
