"""
Hilo People — SQLAlchemy 2.x ORM models: identity and RBAC.

Slice:  P01-S01-T001 — 0001_auth_users_employee_audit migration
Phase:  P01 Auth + Data Foundation
Purpose: Defines ORM models for identity and role-based access control:
         User, EmployeeProfile, Role, Permission, UserRole.

Bounded context: identity — who the user is, what org they belong to, what
roles they hold. Authentication session (tokens) lives in auth.py.

Mapped tables (all created by migration 0001_auth_users_employee_audit.py):
  - users
  - employee_profiles  (FK -> users ON DELETE CASCADE)
  - roles
  - permissions
  - user_roles         (join table: users x roles, FK CASCADE on both)

Key deps:
  - app.db.base        — Base (DeclarativeBase with naming_convention)
  - sqlalchemy==2.0.49 (Mapped, mapped_column, relationship, ForeignKey)
  - sqlalchemy.dialects.postgresql — UUID, JSONB

Source refs:
  - docs/source-of-truth/HILO_PEOPLE_TECHNICAL_GUIDE.md §10.3#users
  - docs/source-of-truth/instrucciones.md §3.1#auth-perfiles
  - 01-non-negotiables.md §Database (index on every WHERE/JOIN field)

Decisions implemented:
  - D3: identity in user.py, session/audit in auth.py (bounded context)
  - D6: user_id NOT NULL on FK references (tighter than §10.3 raw DDL)
  - D8: NO index on employee_profiles.country (YAGNI until P04)
  - D9: NO seed of roles/permissions here (verification_data loader)
  - D10: NO trigger for updated_at (app-controlled, added P01-S02-T007)

Note on column name 'metadata':
  SQLAlchemy reserves the Python attribute 'metadata' on mapped classes (it
  is a class-level attribute holding the MetaData object). The Python attribute
  is named 'extra_metadata' with mapped_column(name='metadata') so the DB
  column name matches §10.3 exactly. Loader.py and fixtures use the DB column
  name directly via SQL text; ORM consumers use the Python attribute name.
"""

from __future__ import annotations

import uuid
from typing import Any

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


# ---------------------------------------------------------------------------
# User — primary identity entity
# ---------------------------------------------------------------------------
class User(Base):
    """ORM model for the `users` table.

    Stores identity and login credentials for every Hilo People user.
    password_hash is hashed with Argon2id (P01-S02-T001 service layer).
    preferred_language is constrained to ('es','en','fr') at DB level
    via CHECK constraint users_language_chk.

    Table: users
    PK: id UUID (gen_random_uuid() via pgcrypto)
    Constraints: UNIQUE(email), CHECK(preferred_language IN ('es','en','fr'))

    Refs: §10.3#users, instrucciones.md §3.1 (email domain validated at app
          layer only; no CHECK on email domain — extensible via whitelist).
    """

    __tablename__ = "users"
    __table_args__ = (
        sa.CheckConstraint(
            "preferred_language IN ('es','en','fr')",
            name="users_language_chk",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        comment="PK UUID generated by pgcrypto gen_random_uuid()",
    )
    email: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        comment="Corporate email — uniqueness at DB; domain validated at app layer",
    )
    password_hash: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        comment="Argon2id hash — NEVER logged or returned to client",
    )
    full_name: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
    )
    status: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        server_default=sa.text("'active'"),
        comment="Account status; enum active|inactive|pending|locked enforced at app layer",
    )
    preferred_language: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        server_default=sa.text("'es'"),
        comment="ISO 639-1 code; CHECK users_language_chk enforces es|en|fr",
    )
    created_at: Mapped[sa.DateTime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
    )
    updated_at: Mapped[sa.DateTime] = mapped_column(
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        comment="Updated by app layer P01-S02-T007 — no DB trigger (D10)",
    )

    # Relationships
    employee_profile: Mapped["EmployeeProfile | None"] = relationship(
        "EmployeeProfile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    user_roles: Mapped[list["UserRole"]] = relationship(
        "UserRole",
        back_populates="user",
        cascade="all, delete-orphan",
    )


# ---------------------------------------------------------------------------
# EmployeeProfile — org-specific data (1:1 with User)
# ---------------------------------------------------------------------------
class EmployeeProfile(Base):
    """ORM model for the `employee_profiles` table.

    Stores organizational metadata for each employee. user_id is both PK and FK
    (1:1 with users). ON DELETE CASCADE ensures the profile is removed when the
    user is deleted (GDPR Art. 17 right-to-erasure).

    Table: employee_profiles
    PK: user_id UUID (FK -> users.id ON DELETE CASCADE)
    Constraints: UNIQUE(employee_id)

    Column names exactly match verification_data/schemas.py EmployeeProfileFixture
    fields: employee_id, brand, society, center, country, department, metadata.
    The Python attribute 'extra_metadata' maps to DB column 'metadata' — SQLAlchemy
    reserves 'metadata' as a class-level attribute.

    Refs: §10.3#users, loader.py contract §7.7 of task pack.
    """

    __tablename__ = "employee_profiles"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE", name="employee_profiles_user_id_fkey"),
        primary_key=True,
        nullable=False,
        comment="PK + FK -> users.id ON DELETE CASCADE (GDPR erasure cascade)",
    )
    employee_id: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        comment="Internal HR employee identifier — globally unique",
    )
    brand: Mapped[str] = mapped_column(sa.Text, nullable=False)
    society: Mapped[str] = mapped_column(sa.Text, nullable=False)
    center: Mapped[str] = mapped_column(sa.Text, nullable=False)
    country: Mapped[str] = mapped_column(sa.Text, nullable=False)
    department: Mapped[str] = mapped_column(sa.Text, nullable=False)
    # DB column is 'metadata'; Python attribute is 'extra_metadata' to avoid
    # conflict with SQLAlchemy's class-level 'metadata' attribute.
    extra_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        server_default=sa.text("'{}'::jsonb"),
        comment="Arbitrary org metadata (JSONB); DB column name is 'metadata'",
    )

    # Relationship
    user: Mapped["User"] = relationship("User", back_populates="employee_profile")


# ---------------------------------------------------------------------------
# Role — named authorization role
# ---------------------------------------------------------------------------
class Role(Base):
    """ORM model for the `roles` table.

    Stores named roles for RBAC. Canonical names consumed by app guards
    (§10.2): 'user', 'admin', 'auditor'. Seed via verification_data loader
    (D9 — not in this migration).

    Table: roles
    PK: id UUID (gen_random_uuid())
    Constraints: UNIQUE(name)
    """

    __tablename__ = "roles"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )
    name: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        comment="Role name (user|admin|auditor). Seeded by verification_data loader.",
    )

    user_roles: Mapped[list["UserRole"]] = relationship(
        "UserRole",
        back_populates="role",
        cascade="all, delete-orphan",
    )


# ---------------------------------------------------------------------------
# Permission — fine-grained permission key
# ---------------------------------------------------------------------------
class Permission(Base):
    """ORM model for the `permissions` table.

    Permission keys for fine-grained access control. Seed via verification_data
    loader (D9). No FK to roles here — role-permission mapping is at app layer.

    Table: permissions
    PK: id UUID (gen_random_uuid())
    Constraints: UNIQUE(key)
    """

    __tablename__ = "permissions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )
    key: Mapped[str] = mapped_column(
        sa.Text,
        nullable=False,
        unique=True,
        comment="Permission key string e.g. 'users:read', 'admin:write'",
    )


# ---------------------------------------------------------------------------
# UserRole — explicit join model (users x roles)
# ---------------------------------------------------------------------------
class UserRole(Base):
    """ORM model for the `user_roles` join table (users x roles).

    Explicit join model (not implicit secondary=) to allow future columns
    (e.g., granted_at, granted_by) without schema breakage.
    Both FKs cascade-delete so removing a user or role cleans up assignments.

    Table: user_roles
    PK: (user_id, role_id) composite
    Constraints: FK -> users.id CASCADE, FK -> roles.id CASCADE

    Refs: §10.3#users, D3 explicit join model for future extensibility.
    """

    __tablename__ = "user_roles"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("users.id", ondelete="CASCADE", name="user_roles_user_id_fkey"),
        primary_key=True,
        nullable=False,
    )
    role_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        sa.ForeignKey("roles.id", ondelete="CASCADE", name="user_roles_role_id_fkey"),
        primary_key=True,
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="user_roles")
    role: Mapped["Role"] = relationship("Role", back_populates="user_roles")
