"""
Hilo People — Cryptographic helpers for verification data.

Slice:  P00-S02-T003 — Verification data loader and reset
Phase:  P00 Scaffold + Design System
Purpose: Provides two operations used at fixture load time:
           1. hash_password(plain) → Argon2id hash stored in users.password_hash
           2. encrypt_secret(plain, key) → Fernet-encrypted string for
              mfa_totp_secrets.secret_encrypted and ai_provider credentials.

         Neither function is called in the UPSERT SET clause — only in the
         INSERT branch — because Argon2 is non-deterministic (random salt) and
         we must NOT re-hash on every update (that would break AC1 idempotency).

Key deps:
  - argon2-cffi==25.1.0 (argon2.PasswordHasher — Argon2id by default)
  - cryptography (Fernet symmetric encryption — already a transitive dep)

Source refs:
  - docs/source-of-truth/HILO_PEOPLE_TECHNICAL_GUIDE.md §10.2 Auth (Argon2)
  - docs/source-of-truth/HILO_PEOPLE_TECHNICAL_GUIDE.md §C.7 (MFA Fernet)
  - 01-non-negotiables.md §Security — passwords hashed with argon2,
    secrets encrypted at rest with Fernet
"""

import os
from functools import lru_cache

from argon2 import PasswordHasher
from cryptography.fernet import Fernet


# ---------------------------------------------------------------------------
# Argon2 password hashing
# ---------------------------------------------------------------------------
@lru_cache(maxsize=1)
def _get_password_hasher() -> PasswordHasher:
    """Return a cached PasswordHasher instance with Argon2id defaults.

    Cached so the same hasher config is reused across the bootstrap run.

    Returns:
        argon2.PasswordHasher with default Argon2id parameters.
    """
    return PasswordHasher()


def hash_password(plain: str) -> str:
    """Hash a plain-text password with Argon2id and return the encoded hash.

    This is called ONLY in the INSERT branch of UPSERT — never in the SET
    branch — because Argon2 uses a random salt and produces a different hash
    each time, which would trigger unnecessary DB updates on every run.

    Args:
        plain: Raw password string from the fixture (e.g. employee_primary.json).

    Returns:
        Argon2id hash string suitable for storing in users.password_hash.

    Raises:
        argon2.exceptions.HashingError: If hashing fails.
    """
    ph = _get_password_hasher()
    return ph.hash(plain)


def verify_password(plain: str, hashed: str) -> bool:
    """Verify a plain password against an Argon2id hash.

    Used during idempotency check: if the stored hash verifies OK, the
    UPSERT SET clause should skip updating password_hash (no re-hash).

    Args:
        plain:  Raw password string.
        hashed: Stored Argon2id hash string.

    Returns:
        True if password matches; False otherwise.
    """
    ph = _get_password_hasher()
    try:
        ph.verify(hashed, plain)
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Fernet symmetric encryption for secrets
# ---------------------------------------------------------------------------
def _get_fernet_key() -> bytes:
    """Read the MFA_ENCRYPTION_KEY env var and return a valid Fernet key.

    Accepts:
      - A raw 32-byte URL-safe base64 key (as generated by Fernet.generate_key()).
      - A plain ASCII string (padded and base64-encoded for convenience in .env).

    Returns:
        Bytes suitable for Fernet(key).

    Raises:
        RuntimeError: If MFA_ENCRYPTION_KEY is not set or malformed.
    """
    raw = os.getenv("MFA_ENCRYPTION_KEY", "")
    if not raw:
        raise RuntimeError(
            "MFA_ENCRYPTION_KEY environment variable is not set. "
            "Generate one with: python3 -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
        )
    try:
        # Accept both raw base64 Fernet keys and plain strings (pad if needed).
        key_bytes = raw.encode() if isinstance(raw, str) else raw
        # Validate the key by instantiating a Fernet object.
        Fernet(key_bytes)
        return key_bytes
    except Exception as exc:
        raise RuntimeError(f"MFA_ENCRYPTION_KEY is not a valid Fernet key: {exc}") from exc


def encrypt_secret(plain: str) -> str:
    """Encrypt a plain-text secret with Fernet (AES-128-CBC + HMAC-SHA256).

    Used for MFA TOTP secrets and AI provider credentials stored in DB.
    The encrypted value is base64url-encoded and safe for TEXT columns.

    Args:
        plain: Plain-text secret (e.g. TOTP base32 string, API key).

    Returns:
        Fernet token as a UTF-8 string.

    Raises:
        RuntimeError: If MFA_ENCRYPTION_KEY is not set or malformed.
    """
    key = _get_fernet_key()
    f = Fernet(key)
    return f.encrypt(plain.encode()).decode()


def decrypt_secret(token: str) -> str:
    """Decrypt a Fernet-encrypted secret token.

    Args:
        token: Fernet token string (from encrypt_secret).

    Returns:
        Decrypted plain-text string.

    Raises:
        RuntimeError: If MFA_ENCRYPTION_KEY is invalid.
        cryptography.fernet.InvalidToken: If the token is corrupt or expired.
    """
    key = _get_fernet_key()
    f = Fernet(key)
    return f.decrypt(token.encode()).decode()
